-- =============================================================================
-- user_info migration
-- 目標：
-- 1) 新增 city / location 欄位
-- 2) 將唯一識別改為 (user_name, user_game_id)
-- 3) 讓同名不同 game_id 可共存
-- 4) 與目前 server.js 的 upsertUserInfo 規則一致
--
-- 使用方式：
-- - Supabase SQL Editor 貼上整段執行
-- - 建議先備份 user_info
-- =============================================================================

BEGIN;

-- 0) 若舊欄位有 NULL，先標準化，避免後續 NOT NULL 失敗
UPDATE public.user_info
SET user_game_id = COALESCE(user_game_id, ''),
    user_location = COALESCE(user_location, '');

-- 1) 新增新欄位（若不存在）
ALTER TABLE public.user_info
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS location TEXT;

-- 2) 由舊 user_location 盡量回填 city/location（保守策略）
--    - 先把 city 設為舊 user_location（若 city 目前為空）
--    - location 預設空字串
UPDATE public.user_info
SET city = CASE
              WHEN COALESCE(city, '') = '' THEN COALESCE(NULLIF(user_location, ''), '')
              ELSE city
           END,
    location = COALESCE(location, '');

-- 3) 設定必要欄位非空（配合服務端規則）
ALTER TABLE public.user_info
  ALTER COLUMN user_name SET NOT NULL,
  ALTER COLUMN user_game_id SET NOT NULL,
  ALTER COLUMN city SET NOT NULL,
  ALTER COLUMN location SET NOT NULL;

-- 4) 確保有單一主鍵 id（若原本沒有）
ALTER TABLE public.user_info
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 5) 移除舊主鍵（通常是 user_name）
DO $$
DECLARE
  pk_name TEXT;
BEGIN
  SELECT conname
  INTO pk_name
  FROM pg_constraint
  WHERE conrelid = 'public.user_info'::regclass
    AND contype = 'p';

  IF pk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.user_info DROP CONSTRAINT %I', pk_name);
  END IF;
END $$;

-- 6) 重新建立主鍵在 id
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = 'public.user_info'::regclass
      AND contype = 'p'
  ) THEN
    ALTER TABLE public.user_info
      ADD CONSTRAINT user_info_pkey PRIMARY KEY (id);
  END IF;
END $$;

-- 7) 先去重，再建立唯一索引 (user_name, user_game_id)
--    若已存在重複，保留 id 最大（最新）一筆
WITH ranked AS (
  SELECT
    id,
    ROW_NUMBER() OVER (
      PARTITION BY user_name, user_game_id
      ORDER BY id DESC
    ) AS rn
  FROM public.user_info
)
DELETE FROM public.user_info u
USING ranked r
WHERE u.id = r.id
  AND r.rn > 1;

CREATE UNIQUE INDEX IF NOT EXISTS user_info_user_name_game_id_uidx
  ON public.user_info (user_name, user_game_id);

COMMIT;

