-- =============================================================================
-- voting_info migration: serial_no 改為「每個 event_id 各自遞增」
-- 目標：
-- 1) 不再讓 serial_no 當全域主鍵
-- 2) 改為 UNIQUE(event_id, serial_no)
-- 3) 保留既有資料可查
--
-- 適用情境：
-- - 目前錯誤: duplicate key value violates unique constraint "voting_info_pkey"
-- - 期望: event_001 的 serial_no=1 與 event_002 的 serial_no=1 可同時存在
-- =============================================================================

BEGIN;

-- 1) 加入 id 欄位當主鍵（若還沒有）
ALTER TABLE public.voting_info
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 2) 找目前主鍵名稱，若存在先移除（通常是 serial_no）
DO $$
DECLARE
  pk_name TEXT;
BEGIN
  SELECT conname
  INTO pk_name
  FROM pg_constraint
  WHERE conrelid = 'public.voting_info'::regclass
    AND contype = 'p';

  IF pk_name IS NOT NULL THEN
    EXECUTE format('ALTER TABLE public.voting_info DROP CONSTRAINT %I', pk_name);
  END IF;
END $$;

-- 3) 設定 id 為新主鍵
ALTER TABLE public.voting_info
  ADD CONSTRAINT voting_info_pkey PRIMARY KEY (id);

-- 4) 若 event_id 有 NULL，補成空字串避免 unique 索引失敗
UPDATE public.voting_info
SET event_id = ''
WHERE event_id IS NULL;

-- 5) 建立每活動序號唯一
CREATE UNIQUE INDEX IF NOT EXISTS voting_info_event_serial_uidx
  ON public.voting_info (event_id, serial_no);

COMMIT;

